// ============================================================
//  VTO Travel — Datos de Tours
// ============================================================

const TOURS = [
  {
    id: 1,
    imagen: "images/tours/tour-1.jpg",
    nombre: "Tesoro de los Valles",
    subtitulo: "Hierve el Agua",
    horario: "8:30 am – 7:00 pm",
    precio: 500,
    descripcion: "Donde la naturaleza se convierte en piedra y maravilla.",
    icon: "fa-water",
    color: "#ff5e3a",
    lugares: [
      "Hierve el Agua",
      "Taller de Tapetes de lana en Teotitlán del Valle",
      "Taller de velas artesanales",
      "Fábrica de mezcal",
      "Árbol del Tule",
      "Zona arqueológica de Mitla",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
      "Degustación de mezcal GRATIS",
    ],
    recoleccion: "8:00 a 8:30 am",
    recomendacion: "Llevar ropa cómoda y desayunar antes de salir.",
    tags: ["Naturaleza", "Arqueología", "Mezcal"],
  },
  {
    id: 2,
    imagen: "images/tours/tour-2.jpg",
    nombre: "La Grandeza Zapoteca",
    subtitulo: "Monte Albán",
    horario: "9:30 am – 5:30 pm",
    precio: 400,
    descripcion: "La grandeza zapoteca que domina los Valles Centrales.",
    icon: "fa-landmark-dome",
    color: "#d97706",
    lugares: [
      "Monte Albán",
      "Taller de alebrijes en San Antonio Arrazola",
      "Fábrica de mezcal ancestral",
      "Barro negro en San Bartolo Coyotepec",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
      "Degustación de mezcal GRATIS",
    ],
    recoleccion: "9:00 a 9:30 am",
    recomendacion: "Llevar ropa cómoda y desayunar antes de salir.",
    tags: ["Arqueología", "Arte", "Mezcal"],
  },
  {
    id: 3,
    imagen: "images/tours/tour-3.jpg",
    nombre: "Sierra Norte",
    subtitulo: "Capulálpam de Méndez",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion: "Aventura, tradición y cultura en lo alto de la sierra.",
    icon: "fa-mountain-sun",
    color: "#059669",
    lugares: [
      "Ixtlán de Juárez",
      "Mirador de cristal",
      "Juegos extremos",
      "Capulálpam de Méndez",
      "Temazcal y medicina tradicional",
      "Las Ánimas",
      "Molenillos y chocolate artesanal",
      "San Pablo Guelatao",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion:
      "Llevar ropa abrigada, calzado cómodo, hidratación y protector solar.",
    tags: ["Aventura", "Naturaleza", "Cultura"],
  },
  {
    id: 4,
    imagen: "images/tours/tour-4.jpg",
    nombre: "Cascadas y Misterios",
    subtitulo: "Río Peñas",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion:
      "Vive la mejor experiencia con nosotros entre cascadas y grutas.",
    icon: "fa-person-swimming",
    color: "#0284c7",
    lugares: ["Peñas Gemelas", "Gruta", "Cascadas de Apoala"],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar ropa cómoda, traje de baño y calzado adecuado.",
    tags: ["Aventura", "Naturaleza", "Cascadas"],
  },
  {
    id: 5,
    imagen: "images/tours/tour-5.jpg",
    nombre: "Puerto Escondido",
    subtitulo: "Playas & Bioluminiscencia",
    horario: "5:30 am – 10:00 pm",
    precio: 700,
    descripcion: "Sol, mar y maravillas naturales en la costa oaxaqueña.",
    icon: "fa-umbrella-beach",
    color: "#2563eb",
    lugares: [
      "Playa Carrizalillo",
      "Playa Bacocho",
      "Liberación de tortugas",
      "Bioluminiscencia en Manialtepec",
      "Playa Zicatela",
      "Mercadito tradicional para desayunar",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "5:30 a 6:00 am",
    recomendacion:
      "Llevar traje de baño, muda adicional, sandalias, ropa cómoda.",
    tags: ["Playa", "Naturaleza", "Aventura"],
  },
  {
    id: 6,
    imagen: "images/tours/tour-6.jpg",
    nombre: "Aventura en las Nubes",
    subtitulo: "Cumbre Tirolesa",
    horario: "8:15 am – 9:00 pm",
    precio: 700,
    descripcion: "Aventura en las nubes con paisajes de ensueño.",
    icon: "fa-cloud-sun",
    color: "#7c3aed",
    lugares: [
      "Senderismo en la cumbre",
      "Columpio al borde del abismo",
      "Temazcal (opcional)",
      "Tirolesa (opcional)",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion:
      "Llevar ropa abrigada, calzado cómodo, hidratación, protector solar y toalla si harán temazcal.",
    tags: ["Aventura", "Adrenalina", "Naturaleza"],
  },
  {
    id: 7,
    imagen: "images/tours/tour-7.jpg",
    nombre: "Cenote & Grutas",
    subtitulo: "El Encanto",
    horario: "8:15 am – 8:00 pm",
    precio: 700,
    descripcion: "Aventura, tradición y cultura en lo alto de la sierra.",
    icon: "fa-gem",
    color: "#0d9488",
    lugares: [
      "Grutas de San Sebastián de las Grutas",
      "Río subterráneo",
      "Cenote",
      "Ríos",
      "Mezcalería",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "7:40 am a 8:15 am",
    recomendacion: "Llevar traje de baño, sandalias, toalla y ropa cómoda.",
    tags: ["Aventura", "Naturaleza", "Mezcal"],
  },
  {
    id: 8,
    imagen: "images/tours/tour-8.jpg",
    nombre: "Tour Alebrijes",
    subtitulo: "Magia Artesanal",
    horario: "9:30 am – 6:00 pm",
    precio: 700,
    descripcion: "Vive la magia de Oaxaca en cada artesanía.",
    icon: "fa-palette",
    color: "#db2777",
    lugares: [
      "Barro Negro y Rojo",
      "Taller de Alebrijes",
      "Telar de Cintura",
      "Ex Convento de Santo Domingo",
      "Mercado de Ocotlán de Morelos",
    ],
    incluye: [
      "Pick-up en hotel o airbnb",
      "Seguro de viajero",
      "Coordinador de viaje",
      "Transporte redondo",
      "Guía",
    ],
    recoleccion: "8:50 am y 9:30 am",
    recomendacion: "Llevar protector solar, ropa cómoda y fresca.",
    tags: ["Cultura", "Arte", "Artesanías"],
  },
];